---
- hosts: all
  tasks:
  - name: Fecha y Hora
    command: date
    register: fecha
  - debug:
      msg: "FECHA: {{ fecha.stdout }}"
  
  - name: Copia Plantilla
    command: cp /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM_ORIG /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM
    register: copia
      
  - name: Backup Doc1 a las rutas ingresadas
    blockinfile:
      path: /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM
      insertafter: "-trees"
      block: |
        {{ RUTAS }}                
    register: resultado
    
  - name: Copiar archivo a ruta destino
    copy:
      src: /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM
      dest: /tmp
      mode: 0444
    delegate_to: localhost
    register: copia2
