---
- hosts: all
  become: yes
  tasks:
  - name: Upgrade all packages CentOS - Red Hat - Oracle Linux
    yum:
      name: '*'
      state: latest
    register: result
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Oracle Linux Server'

  - name: Update Cache Debian - Ubuntu
    apt:
      update_cache: yes
    register: result1
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Upgrade all packages Debian - Ubuntu
    apt:
      name: '*'
      state: latest
    register: result2
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
  - name: Reinicio de Servidores
    reboot:
      msg: "El servidor se reiniciará en 15 segundos desde Ansible."
      pre_reboot_delay: 15  # Espera 15 segundos antes de reiniciar
      post_reboot_delay: 30  # Espera 30 segundos después del reinicio antes de marcar como disponible
      reboot_timeout: 600  # Tiempo máximo de espera para que el servidor vuelva a estar accesible
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Oracle Linux Server'

