---
- hosts: all
  tasks:
  - name: Backup Doc1 a las rutas ingresadas
    blockinfile:
      path: /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM
#     backup: yes
#     marker: "# {mark} ANSIBLE MANAGED BLOCK "
      insertafter: "-trees"
      block: |
        {{ RUTAS }}                
    register: resultado
