---
- hosts: all
  tasks:
  - name: Consulta SQL VADP Antes
    win_shell: sqlcmd -S 172.22.1.35\commvault -i G:\consulta.sql
    register: result1
  - debug: var=result1.stdout_lines

  - name: Ejecutar Modificación SQL VADP
    win_shell: sqlcmd -S 172.22.1.35\commvault -i G:\cambia_transporte.sql
    register: result2
  - debug: var=result2.stdout_lines
    
  - name: Consulta SQL VADP Después
    win_shell: sqlcmd -S 172.22.1.35\commvault -i G:\consulta.sql
    register: result3
  - debug: var=result3.stdout_lines
