---
- hosts: "{{ HOST }}"
  tasks:
  - name: Nombre Host
    command: hostname
    register: hostname
  - debug:
      msg: "HOSTNAME: {{ hostname.stdout }}"
      
  - name: Configurar Certificado Data Protector
    command: /opt/omni/bin/omnicc -secure_comm -configure_peer prdpvltoigap.previsora.col -accept_host
    register: certri
  - debug: var=certri.stdout_lines
