---
- hosts: all

  vars:
    comandos: "{{ COMANDO }}"

  tasks:
  - name: Versión Kernel
    command: uname -nsr
    register: res1
  - debug: 
    msg: "VERSION DE KERNEL: "
    var=res1.stdout_lines
    when: comandos == "UNAME"
   
  - name: Archivo Host
    command: cat /etc/hosts
    register: res2
  - debug: var=res2.stdout_lines
    when: comandos == "CAT"
      
  - name: Información Server
    command: hostnamectl
    register: res3
  - debug: var=res3.stdout_lines
    when: comandos == "HOST"
    
  - name: Información VG
    command: vgdisplay
    register: res4
  - debug: var=res4.stdout_lines
    when: comandos == "VGS"
    
  - name: Estado Memoria
    command: free -h
    register: res5
  - debug: var=res5.stdout_lines
    when: comandos == "MEM"
 
  - name: Dispositivos SCSI
    command: lsscsi
    register: res6
  - debug: var=res6.stdout_lines
    when: comandos == "SCSI"
    
  - name: Discos
    command: fdisk -l
    register: res7
  - debug: var=res7.stdout_lines
    when: comandos == "DISC"
