---
- hosts: all
  tasks:
  - name: Fecha y Hora Actual
    command: date
    register: date
  - debug:
      msg: "FECHA: {{ date.stdout }}"
  
  - name: Duplicar Plantilla
    command: cp /automat/DOC1_COMHP36_FS_F_DEM_ORIG /automat/DOC1_COMHP36_FS_F_DEM
    register: duplica
      
  - name: Modificar Rutas
    blockinfile:
      path: /automat/DOC1_COMHP36_FS_F_DEM
      insertafter: "-trees"
      block: |
        {{ RUTAS }}                
    register: rutas
    
  - name: Copiar Archivo Destino
    command: cp /automat/DOC1_COMHP36_FS_F_DEM /tmp
    register: copia

  - name: Cambiar Permisos Destino
    command: chmod 777 /tmp/DOC1_COMHP36_FS_F_DEM
    register: permisos
      msg: "PROCESO TERMINADO CON EXITO"
