---
- hosts: all
  tasks:

- name: Enviar correo
  mail:
    host: 172.22.88.6
    port: 25
    subject: "Reporte Ejecución"
    body: "Se adjunta reporte"
    to: gustavo.lamprea@claro.com.co
    from: ansible@claro.com.co
