---
- hosts: all
  tasks:
  - name: Eliminar Log Antiguo en Servidor
    win_find:
      paths: C:\
      patterns: 'AnsibleWinUpdate.txt'
      age: 0d
      file_type: file
    register: files_to_delete

  - name: Ansible Remove Files Older
    win_file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
    
  - name: Install All Updates
    ansible.windows.win_updates:
      category_names: '*'
      reboot: true
      log_path: C:\AnsibleWinUpdate.txt
    register: update_result
  
  - name: Reinicio de Servidores
    win_reboot:
      reboot_timeout: 600  # Tiempo máximo de espera en segundos
      msg: "El servidor se reiniciará en 10 segundos desde Ansible."
      pre_reboot_delay: 15  # Espera 15 segundos antes de reiniciar

#  - name: Reiniciar Servidor si es requerido
#    win_reboot:
#    when: update_result.reboot_required

# - name: Reinicio de Servidor
#   ansible.windows.win_reboot:
#     msg: "Reiniciado por Ansible"
#     pre_reboot_delay: 5
#     post_reboot_delay: 10
