---
- hosts: all 
  tasks:
  - name: Rutas Persistentes Antes
    command: route -n
    register: antes
  - debug: 
      msg: "RUTAS PERSISTENTES ANTES:"
      var=antes.stdout_lines
  
  - name: Adicionar Rutas Persistentes Linux
    command: route add -net {{ RED }} netmask 255.255.255.0 gw 172.22.1.1
    register: rutas
 
  - name: Rutas Persistentes Después
    command: route -n
    register: desp
  - debug: var=desp.stdout_lines
