---
- hosts: all
  gather_facts: no

  vars:
    comandos: "{{ COMANDO }}"
    lista_comandos:
      UNAME: "uname -nsr"
      CAT: "cat /etc/hosts"
      HOST: "hostnamectl"
      VGS: "vgs"
      MEM: "free -h"
      SCSI: "lsscsi"
      DISC: "fdisk -l"
      LVS: "lvs"
      UPTIME: "uptime"
      UPDATE: "yum update -y"
      UPGRADE: "yum upgrade -y"
      
  tasks:
    - name: Validar que el Comando exista en lista_comandos
      fail:
        msg: "El comando {{ comandos }} no existe en lista_comandos"
      when: comandos not in lista_comandos

    - name: Ejecutando Comando Seleccionado
      command: "{{ lista_comandos[comandos] }}"
      register: salida
      when: comandos in lista_comandos

    - name: Resultado en Consola
      debug:
        var: salida.stdout_lines
      when: salida is defined

    - name: Guardar Resultados en FACT
      set_fact:
        resultados: "{{ resultados | default({}) | combine({ inventory_hostname: salida.stdout_lines }) }}"
      when: salida is defined

- hosts: CENTOS7_LNX
  gather_facts: yes

  vars:
    lista_comandos:
      UNAME: "uname -nsr"
      CAT: "cat /etc/hosts"
      HOST: "hostnamectl"
      VGS: "vgs"
      MEM: "free -h"
      SCSI: "lsscsi"
      DISC: "fdisk -l"
      LVS: "lvs"
      UPTIME: "uptime"
      UPDATE: "yum update -y"
      UPGRADE: "yum upgrade -y"

  tasks:
    - name: Crear Carpeta Reportes si no existe
      file:
        path: /tmp/reportes
        state: directory
        mode: '0755'

    - name: Consolidar Resultados de los Hosts
      set_fact:
        resultados: "{{ hostvars | dict2items 
                        | selectattr('value.resultados','defined') 
                        | map(attribute='value.resultados') 
                        | list 
                        | combine }}"

    - name: Generar Reporte en HTML
      template:
        src: reportewhen.j2
        dest: "/tmp/reportes/reporte_{{ COMANDO }}.html"

    - name: Mostrar Ruta del Reporte
      debug:
        msg: "REPORTE GENERADO EN: /tmp/reportes/reporte_{{ COMANDO }}.html"










