---
- hosts: all 
  tasks:
  - name: Adicionar Rutas Persistentes Linux
    command: route add -net {{ RED }} netmask 255.255.255.0 gw 172.22.1.1
    register: rutaswin
  - debug: var=rutaswin.stdout_lines
 
