---
- hosts: "{{ HOST }}"
  gather_facts: no
  tasks:
  - name: Nombre Host
    win_command: cmd.exe /c hostname
    register: hostname
  - debug:
      msg: "HOSTNAME: {{ hostname.stdout }}"
        
  - name: Configurar Certificado Data Protector Triara
    win_command: cmd.exe /c omnicc -secure_comm -configure_peer prdpvwpdpap.previsora.col -accept_host
    register: certri
  - debug: var=certri.stdout_lines
