---
- hosts: all
  gather_facts: no
  tasks:
  - name: Nombre Host
    win_command: cmd.exe /c hostname
    register: hostname
  - debug:
      msg: "HOSTNAME: {{ hostname.stdout }}"
        
  - name: Exportar Cliente de Data Protector
    win_command: cmd.exe /c omnicc -update_host "{{ CLIENTE }}" -accept_host
    register: importdp
  - debug: var=importdp.stdout_lines
