---
- hosts: all
  tasks:
  - name: Copia Plantilla
    command: cp /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM_ORIG /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM
    register: copia
   - debug: var=copia.stdout_lines
      
  - name: Backup Doc1 a las rutas ingresadas
    blockinfile:
      path: /var/lib/awx/projects/glamprea/DOC1_COMHP36_FS_F_DEM
      insertafter: "-trees"
      block: |
        {{ RUTAS }}                
    register: resultado
