---
- hosts: all 
  tasks:
  - name: Rutas Persistentes Antes
    command: route -n
    register: antes
  - debug: var=antes.stdout_lines
  
  - name: Adicionar Rutas Persistentes Linux
    command: route add -net {{ RED }} netmask {{ MASK }} gw {{ GAT }}
    register: rutas
 
  - name: Rutas Persistentes Después
    command: route -n
    register: desp
  - debug: var=desp.stdout_lines
