---
- hosts: "{{ ALL }}"
  tasks:
  - name: Fecha
    win_command: cmd.exe /c date /t
    register: fecha
  - debug:
      msg: "FECHA: {{ fecha.stdout }}"

  - name: Hora
    win_command: cmd.exe /c time /t
    register: hora
  - debug:
      msg: "HORA: {{ hora.stdout }}"
      
  - name: Nombre Host
    win_command: cmd.exe /c hostname
    register: hostname
  - debug:
      msg: "HOSTNAME: {{ hostname.stdout }}"
        
  - name: Exportar Cliente de Data Protector
    win_command: cmd.exe /c omnicc -export_host "{{ CLIENTE }}"
    register: exportdp
  - debug: var=exportdp.stdout_lines
