---
- hosts: all
  gather_facts: no

  vars:
    comandos: "{{ COMANDO }}"
    lista_comandos:
      UNAME: "uname -nsr"
      CAT: "cat /etc/hosts"
      HOST: "hostnamectl"
      VGS: "vgs"
      MEM: "free -h"
      SCSI: "lsscsi"
      DISC: "fdisk -l"
      LVS: "lvs"
      UPTIME: "uptime"
      UPDATE: "yum update"
      UPGRADE: "yum upgrade"

  tasks:
    - name: Ejecutando Comando Seleccionado
      shell: "{{ lista_comandos[comandos] }}"
      register: salida
      when: comandos in lista_comandos

    - name: Resultado
      debug:
        var: salida.stdout_lines
      when: salida is defined

    - name: Guardar resultados en fact
      set_fact:
        resultados: "{{ resultados | default({}) | combine({ inventory_hostname: salida.stdout_lines }) }}"
      when: salida is defined

- hosts: CENTOS7_LNX
  gather_facts: no
  tasks:
    - name: Crear carpeta de reportes si no existe
      file:
        path: /tmp/reportes
        state: directory
        mode: '0755'

    - name: Generar Reporte en HTML
      template:
        src: reportewhen.j2
        dest: "/tmp/reportes/reporte_{{ comandos }}.html"
      vars:
        resultados: "{{ hostvars | dict2items | selectattr('value.resultados','defined') | map(attribute='value.resultados') | first }}"
        lista_comandos:
          UNAME: "uname -nsr"
          CAT: "cat /etc/hosts"
          HOST: "hostnamectl"
          VGS: "vgs"
          MEM: "free -h"
          SCSI: "lsscsi"
          DISC: "fdisk -l"
          LVS: "lvs"
          UPTIME: "uptime"

    - name: Mostrar Ruta del Reporte
      debug:
        msg: "Reporte generado en /tmp/reportes/reporte_{{ comandos }}.html"
