---
- hosts: all
  gather_facts: no

  vars:
    smtp_server: "172.22.88.195"
    smtp_port: 25
    correo_destino: "gustavo.lamprea@claro.com.com"
    correo_origen: "ansible@claro.com.co"

  tasks:

    - name: Obtener hostname
      win_command: cmd.exe /c hostname
      register: hostname

    - name: Exportar Cliente Data Protector
      win_command: cmd.exe /c omnicc -update_host "{{ CLIENTE }}"
      register: exportdp

    - name: Generar HTML
      set_fact:
        html_reporte: "{{ lookup('template', 'reporte.html.j2') }}"

    - name: Enviar correo
      delegate_to: localhost
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        to: "{{ correo_destino }}"
        from: "{{ correo_origen }}"
        subject: "Resultado Import Host Data Protector - {{ hostname.stdout }}"
        subtype: html
        body: "{{ html_reporte }}"
