---
- hosts: all
  gather_facts: no
  tasks:
  - name: Nombre Host
    win_command: cmd.exe /c hostname
    register: hostname
  - debug:
      msg: "HOSTNAME: {{ hostname.stdout }}"
        
  - name: Exportar Cliente de Data Protector
    win_command: cmd.exe /c ping "{{ CLIENTE }}"
    register: exportdp
  - debug: var=exportdp.stdout_lines
