---
- hosts: all

  vars:
    comandos: "{{ COMANDO }}"

  tasks:
  - name: Versión Kernel
    command: uname -nsr
    register: res1
  - debug: var=res1.stdout_lines
    when: comandos == "UNAME"
   
  - name: Archivo Host
    command: cat /etc/hosts
    register: res2
  - debug: var=res2.stdout_lines
    when: comandos == "CAT"
      
  - name: Información Server
    command: hostnamectl
    register: res3
  - debug: var=res3.stdout_lines
    when: comandos == "HOST"
