---
- hosts: all
  gather_facts: no

  vars:
    comandos: "{{ COMANDO }}"
    lista_comandos:
      UNAME: "uname -nsr"
      CAT: "cat /etc/hosts"
      HOST: "hostnamectl"
      VGS: "vgs"
      MEM: "free -h"
      SCSI: "lsscsi"
      DISC: "fdisk -l"
      LVS: "lvs"
      UPTIME: "uptime"
      UPDATE: "yum update"
      UPGRADE: "yum upgrade"

  tasks:
    - name: Ejecutando Comando Seleccionado
      shell: "{{ lista_comandos[comandos] }}"
      register: salida
      when: comandos in lista_comandos

    - name: Resultado
      debug:
        var: salida.stdout_lines
      when: salida is defined

