---
- hosts: all
  tasks:
  - name: Ejecutar Consulta SQL
    win_shell: sqlcmd -S 172.22.1.35\commvault -i G:\consulta.sql >> G:\Resultado.html
    register: result1
  
  - name: Ejecutar Consulta SQL
    win_shell: sqlcmd -S 172.22.1.35\commvault -i G:\consulta.sql
    register: result2
  - debug: var=result2.stdout_lines
