---
- hosts: all
  tasks:
  - name: Copiar Script a Servidor
    win_copy:
      src: /var/lib/awx/projects/glamprea/Consultahtml.ps1
      dest: C:\Temp\Consultahtml.ps1

  - name: Ejecutar Script en PowerShell
    win_command: powershell.exe -ExecutionPolicy ByPass -File C:\Temp\Consultahtml.ps1
    register: result
  
  - name: Eliminar Script en Servidor
    win_find:
      paths: C:\Temp
      patterns: 'Consultahtml.ps1'
      age: 0d
      file_type: file
    register: files_to_delete1

  - name: Ansible Remove Files Older Script
    win_file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete1.files }}"
