---
- hosts: all
  connection: local
  tasks:
    - vmware_guest:
        hostname: 172.22.4.65
        username: 'vmware.powercli@DATACENTERDHS.LOCAL'
        password: '4Ut0m4t1z4c10n.'
        validate_certs: False
        name: TESTVM_"{{ item }}"
        template: 'Windows_Server2012_R2_Standard_x64'
        datacenter: 'VDC_PRUEBAS'
        cluster: 'CLT_BACKUP'
        folder: '/Discovered virtual machine'
        state: poweredon
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy
      with_items:
        - 1
        - 2
