---
- hosts: all
  connection: local
  tasks:
    - vmware_guest:
        hostname: 172.22.4.65
        username: 'vmware.powercli@DATACENTERDHS.LOCAL'
        password: '4Ut0m4t1z4c10n.'
        validate_certs: False
        name: "TESTVM_00{{ item }}"
        template: 'Windows_Server2012_R2_Standard_x64'
        disk:
        - size_gb: 130
          type: thin
          datastore: 3PAR_TFM1523_R6_N4_ID002_BACKUP_4TB
        hardware:
          memory_mb: 2048
          num_cpus: 2
          num_cpu_cores_per_socket: 2
          scsi: paravirtual
        networks:
        - name: VM Network
#         ip: 10.10.10.100
#         netmask: 255.255.255.0
#         gateway: 192.168.1.1
#         dns_servers:
#         - 192.168.1.1
#         - 192.168.1.2
          device_type: vmxnet3
        customization:
          hostname: TESTVM_001
        datacenter: 'VDC_PRUEBAS'
        cluster: 'CLT_BACKUP'
        folder: '/Discovered virtual machine'
        state: poweredon
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy
      with_items:
        - 1
#       - 2
#       - 3
